schema_version: 1

context:
  version: "1.2.3"

package:
  name: PyMySQL
  version: ${{ version }}

source:
  url: https://github.com/PyMySQL/PyMySQL/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 9f3589beee81491566794fb9678ec2c7e54cc5d86605032b48e1520b6641aade

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=77
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - pymysql
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - '*'

about:
  license: MIT
  license_file: LICENSE
  summary: Pure Python MySQL Driver
  description: |
    This package contains a pure-Python MySQL client library. The goal of
    PyMySQL is to be a drop-in replacement for MySQLdb and work on CPython,
    PyPy and IronPython.
  homepage: http://github.com/PyMySQL/PyMySQL
  repository: https://github.com/PyMySQL/PyMySQL
  documentation: http://pymysql.readthedocs.io/

extra:
  recipe-maintainers:
    - djsutherland
    - synapticarbors
    - thewchan
